# Generated by Django 6.0.5 on 2026-05-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentenrollment', '0002_enrollmentrequest_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentreceipt',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enrollmentreceipt',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentreceipt',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollmentreceipt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
