"""
Django settings for ubgraduateschool project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path  # Used to build filesystem paths in a cross-platform way

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# __file__ is this settings.py file; .resolve().parent.parent goes up two levels to the project root
BASE_DIR = Path(__file__).resolve().parent.parent


def env_list(name, default=""):
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Used by Django to sign cookies, sessions, and CSRF tokens
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-s3=hjs10z$6b2452+yu*81q*va1!6rkuvsok%*d8mkm0v2lp38',
)

# SECURITY WARNING: don't run with debug turned on in production!
# When True, Django shows detailed error pages and serves static files directly
DEBUG = env_bool('DEBUG', default=not env_bool('VERCEL'))

# List of hostnames that this Django site can serve; empty means only localhost in DEBUG mode
ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,.vercel.app',
)

CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    default='https://*.vercel.app',
)


# Application definition

# All Django apps that are active in this project
INSTALLED_APPS = [
    'django.contrib.admin',        # Django's built-in admin site
    'django.contrib.auth',         # Authentication framework (users, passwords, permissions)
    'django.contrib.contenttypes', # Framework for generic relations between models
    'django.contrib.sessions',     # Server-side session storage
    'django.contrib.messages',     # One-time notification messages (flash messages)
    'django.contrib.staticfiles',  # Manages static files (CSS, JS, images)
    'landingpage',                 # Landing page, login, logout, and registration
    'studenthome',                 # Student home page with tabs and enrollment form
    'studentenrollment',           # Dedicated enrollment form and confirmation page
    'studentprofile',              # Student profile view, edit, and photo upload
    'bookmanagement',              # Book claim form and claimed books list
    'admindash',                   # Admin dashboard for managing courses, subjects, and enrollments
]

# Middleware is a list of hooks that process every request and response
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',            # Enforces HTTPS and security headers
    'whitenoise.middleware.WhiteNoiseMiddleware',               # Serves collected static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',     # Enables session support on every request
    'django.middleware.common.CommonMiddleware',                # Handles URL normalisation (trailing slashes)
    'django.middleware.csrf.CsrfViewMiddleware',                # Protects POST forms against CSRF attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Attaches the logged-in user to every request
    'django.contrib.messages.middleware.MessageMiddleware',     # Enables flash messages in templates
    'django.middleware.clickjacking.XFrameOptionsMiddleware',   # Prevents the site from being embedded in iframes
]

# Points Django to the root URL configuration module
ROOT_URLCONF = 'ubgraduateschool.urls'

# Template engine configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Use Django's built-in template engine
        'DIRS': [BASE_DIR / 'templates'],  # Also look for templates in the project-level templates/ folder
        'APP_DIRS': True,                  # Automatically find templates inside each app's templates/ subfolder
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',       # Adds the current HttpRequest to template context
                'django.contrib.auth.context_processors.auth',      # Adds the logged-in user and permissions to context
                'django.contrib.messages.context_processors.messages',  # Adds flash messages to context
            ],
        },
    },
]

# Points Django to the WSGI application used by production servers (e.g. gunicorn)
WSGI_APPLICATION = 'ubgraduateschool.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use DATABASE_URL in production; fall back to SQLite for local development.
DATABASE_URL = os.environ.get('DATABASE_URL')
if env_bool('VERCEL') and not DATABASE_URL:
    raise ImproperlyConfigured('DATABASE_URL must be set on Vercel.')

DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL or f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# A list of validators that enforce password strength rules
AUTH_PASSWORD_VALIDATORS = [
    {
        # Rejects passwords that are too similar to the user's personal information
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Rejects passwords shorter than 8 characters (Django default)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # Rejects commonly used passwords (e.g. "password", "123456")
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Rejects passwords that consist entirely of numbers
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'  # Default language for the application

TIME_ZONE = 'UTC'  # All datetimes are stored and displayed in UTC

USE_I18N = True  # Enable Django's translation framework

USE_TZ = True  # Store datetimes as timezone-aware objects in the database


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'                                # URL prefix for serving static files
STATICFILES_DIRS = [BASE_DIR / 'staticfiles']          # Source static files committed with the app
STATIC_ROOT = BASE_DIR / 'staticfiles_build' / 'static' # collectstatic output for production
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'                      # URL prefix for serving user-uploaded files
MEDIA_ROOT = BASE_DIR / 'media'           # Directory on disk where uploaded files are saved

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Tell Django to use our custom user model instead of the built-in User model
AUTH_USER_MODEL = 'landingpage.CustomUser'

# Redirect unauthenticated users to the landing page (root URL) instead of /accounts/login/
LOGIN_URL = '/'

# Authentication backends tried in order when authenticate() is called
AUTHENTICATION_BACKENDS = [
    'landingpage.backends.StudentBackend',          # Allows students to log in with id_number + password
    'django.contrib.auth.backends.ModelBackend',    # Default backend: allows admins to log in with username + password
]
