# Generated by Django 6.0.3 on 2026-05-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
