# Generated by Django 6.0.3 on 2026-05-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0002_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Summer', 'Summer')], default='1st Semester', max_length=15),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year')], default='1st Year', max_length=15),
        ),
    ]
